# Generated by Django 2.1.5 on 2019-02-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.IntegerField()),
                ('contesttype', models.IntegerField()),
                ('lname', models.CharField(max_length=128)),
                ('fname', models.CharField(max_length=128)),
                ('tel', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('size', models.IntegerField()),
                ('gender', models.IntegerField(editable=False)),
                ('food', models.IntegerField()),
                ('tlname', models.CharField(max_length=128)),
                ('tfname', models.CharField(max_length=128)),
                ('register_at', models.DateTimeField()),
            ],
        ),
    ]
