# Generated by Django 2.1.5 on 2019-02-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='register_at',
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.IntegerField(),
        ),
    ]
