# Generated by Django 2.1.5 on 2019-02-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0002_auto_20190215_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contesttype',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='food',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='school',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='size',
            field=models.CharField(max_length=128),
        ),
    ]
