# Generated by Django 2.1.5 on 2019-02-15 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0003_auto_20190215_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='tel',
            new_name='phone',
        ),
    ]
