# Generated by Django 2.1.5 on 2019-02-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0005_auto_20190215_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='fname',
            new_name='allergy',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='lname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='tfname',
        ),
        migrations.RemoveField(
            model_name='person',
            name='tlname',
        ),
    ]
