# Generated by Django 2.1.5 on 2019-02-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0006_auto_20190218_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='allergy',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
